### PR TITLE
Handle invalid X-Robots-Tag header values

### PR DESCRIPTION
**Pull request by Mickael-van-der-Beek**
In cases where the `X-Robots-Tag` header value is invalid, the regular expression will return `null` which will break the line after when it is assumed that `result` is an array and an element is accessed by index.

This fix will make the code fallback to the default value of `result`.

Example of a failing case (found in the wild): `'noindex, nofollow\nnosnippet, noarchive'`

### CODE REVIEW

**Comment by Mickael-van-der-Beek** [comment]
@stevenvachon Could this PR be merged?

**Comment by stevenvachon** [comment]
@Mickael-van-der-Beek please rebase

**Comment by Mickael-van-der-Beek** [comment]
@stevenvachon Done. Sorry for the delay.

**Comment by stevenvachon** [comment]
@Mickael-van-der-Beek the coverage dropped

**Comment by stevenvachon** [comment]
This has been implemented on master branch.

**Pull request closed without merging**
